version: 2

updates:
  # npm - dependencies
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Tokyo
    cooldown:
      default-days: 7
    allow:
      - dependency-type: production
    versioning-strategy: widen

  # npm - devDependencies
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Tokyo
    cooldown:
      default-days: 7
    allow:
      - dependency-type: development
    groups:
      devDependencies:
        patterns:
          - "*"
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Tokyo
    cooldown:
      default-days: 7
    groups:
      official-actions:
        patterns:
          - "actions/*"
